### ISSUE TITLE
[Knob] Dragging the knob does not work on touch screen [Internet Explorer] or [Microsoft Edge]

### ISSUE THREAD

**Issue by simonbates** [dinukadesilva/music-ctrls#101]
On a Windows 10 computer with a touch screen (a Microsoft Surface), I can change the value of a knob controller by tapping but I cannot change the value by dragging. If I drag, I instead move the page.

**Comment by simonbates** [comment]
Verified.

**Comment by dinukadesilva** [comment]
Thanks @simonbates 

I raised another issue for that

https://github.com/dinukadesilva/music-ctrls/issues/105
