### ISSUE TITLE
Can't get the demos to work on the master branch

### ISSUE THREAD

**Issue by colinbdclark** [dinukadesilva/music-ctrls#109]
Hi @dinukadesilva, I was trying out your master branch today to see how things are progressing, but I wasn't able to get it to work. 

I ran <code>npm install</code> and then <code>grunt</code>. In the case of the second command, it looks like the build task is working successfully, but the tests are failing. When I try to load the demo pages using a web server (both with the <code>grunt demo</code> task or with my own copy of nginx), I get errors related to D3 not being loaded.

Is there a branch I should be working with instead of master, or am I missing any steps to try out your components?

**Comment by dinukadesilva** [comment]
@colinbdclark

You should have done a bower install before the grunt task as mentioned in the readme. Are u sure the you have done that.

**Comment by dinukadesilva** [comment]
@colinbdclark 

I tested this just now, and it was working fine. Could you please provide more information about the environment you are in.

**Comment by colinbdclark** [comment]
Hi Dinuka,

You're right. I missed the bower step in the instructions. My bad.

Out of curiosity, is there a reason why you're sourcing some dependencies from npm and others from Bower, instead of just using one of them?
