### ISSUE TITLE
Run build as a "postinstall" script...

### ISSUE THREAD

**Issue by the-t-in-rtf** [dinukadesilva/music-ctrls#112]
I want to use the controls as a bundled dependency.  It would be helpful if you added a script in your package.json that bundles the scripts after the package is installed, as in:

```
scripts :{
  "postinstall": "grunt build"
}
```

This would require moving the dependencies around a little.  Happy to prepare a pull request myself if you're OK with the approach.

**Comment by dinukadesilva** [comment]
sure..... thanks for being interested in contributing to sisiliano.
Cheers... !!!!

**Comment by dinukadesilva** [comment]
you are welcome to do a pull request @the-t-in-rtf

**Comment by the-t-in-rtf** [comment]
I just submitted a PR for this and other minor cleanup.

**Comment by the-t-in-rtf** [comment]
Hi, @dinukadesilva.  What was the outcome here?  Were the changes merged somehow?  Were they not acceptable for some reason.  Please advise.

**Comment by dinukadesilva** [comment]
Hi @the-t-in-rtf  your recent PR https://github.com/dinukadesilva/music-ctrls/pull/117 fixes this. So, I closed this issue.

**Comment by the-t-in-rtf** [comment]
It's been a while, thanks for reminding me.
