### ISSUE TITLE
[Knob] aria-describedby should point to other element by id

### ISSUE THREAD

**Issue by simonbates** [dinukadesilva/music-ctrls#44]
In your current implementation, you have something along the following:

```
<div ... role="slider" ... aria-describedby="Use up and down keys
to increase and decrease the value. If you are using the mouse,
Drag around the center to adjust the value" ... >
```

It should instead be structured more like:

```
<div id="music-ctrls-knob-description">Use up and down keys to
increase and decrease the value. If you are using the mouse,
Drag around the center to adjust the value</div>

<div ... role="slider" ... aria-describedby="music-ctrls-knob-description" ... >
```

See also:

- https://www.w3.org/TR/wai-aria/states_and_properties#aria-describedby
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute

**Comment by dinukadesilva** [comment]
This has been fixed by #50 which introduces a new generic component for this purpose.
