### ISSUE TITLE
[Knob] Mouse control on Firefox only works when value approximately 45% - 55%

### ISSUE THREAD

**Issue by simonbates** [dinukadesilva/music-ctrls#53]
On Firefox, it is only possible to initiate change with the mouse if the mouse cursor is positioned in the range of approximately 45% to 55%. Outside that range, it is not possible to initiate change of the value with the mouse.

This issue does not appear on Chrome.

**Comment by dinukadesilva** [comment]
@simonbates Can you provide more details about this...... because it seems the knob is working very well in firefox for me.

**Comment by simonbates** [comment]
This appears to be working for me now -- maybe another change has fixed?

I'll close this issue.

**Comment by simonbates** [comment]
I'm still seeing this on my home computer (but not my work computer, which is weird).

Computer that I'm seeing the issue on:

- Firefox 47.0
  - No extensions
  - Plugins: OpenH264 Video Codec
- Ubuntu 16.04.1 LTS

**Comment by simonbates** [comment]
Okay, we were able to figure this out. This issue is seen when the page zoom is increased in Firefox. At 100% page zoom, the controls act as desired. When the page zoom is increased, say to 200%, the controls have problems.

**Comment by dinukadesilva** [comment]
@simonbates @sepidehshahi

This issue has been fixed now, Could you please verify this again.

**Comment by simonbates** [comment]
Yes, I confirm that I am no longer seeing this issue. I verified at 200% zoom on Firefox.
