### ISSUE TITLE
[Linear slider] Is it not possible to change the value with the mouse using the slider handle or track on Firefox

### ISSUE THREAD

**Issue by simonbates** [dinukadesilva/music-ctrls#54]
It is possible to grab the value label and change the value with that but it is not possible to grab the handle itself or to click on the track. This issue occurs on Firefox.

The slider behaves as expected on Chrome.

**Comment by dinukadesilva** [comment]
@simonbates Can you provide more details about your Firefox version and the system configurations.....

By the way, if you are referring whether it's controllable from outside of the knob when the mouse-down is active, it's still in progress in development

**Comment by simonbates** [comment]
This appears to be working for me now -- maybe another change has fixed?

I am seeing some undesirable drag and drop behaviour though -- we'll need to figure out a fix for drag and drop and SVGs as it is affecting all the controls with click and drag motion.

I'll close this issue.

**Comment by simonbates** [comment]
I'm still seeing this on my home computer (but not my work computer, which is weird).

Computer that I'm seeing the issue on:

- Firefox 47.0
  - No extensions
  - Plugins: OpenH264 Video Codec
- Ubuntu 16.04.1 LTS

**Comment by dinukadesilva** [comment]
@simonbates  I tested in;
Firefox 47.0
ubuntu 14.04 LTS

And that worked. But there was a little slowness than chrome.

**Comment by simonbates** [comment]
Okay, we were able to figure this out. This issue is seen when the page zoom is increased in Firefox. At 100% page zoom, the controls act as desired. When the page zoom is increased, say to 200%, the controls have problems.

**Comment by dinukadesilva** [comment]
@simonbates @sepidehshahi

This issue has been fixed now, Could you please verify this again.

**Comment by simonbates** [comment]
Yes, I confirm that I am no longer seeing this issue. I verified at 200% zoom on Firefox.
