### ISSUE TITLE
[Linear Slider] Finalizing the UI design

### ISSUE THREAD

**Issue by dinukadesilva** [dinukadesilva/music-ctrls#58]

**Comment by dinukadesilva** [comment]
Here are the latest designs of the linear slider

![image](https://cloud.githubusercontent.com/assets/10680296/17049279/f6e4d616-5009-11e6-86d5-1bedf6a3b269.png)


![image](https://cloud.githubusercontent.com/assets/10680296/17049295/11df9672-500a-11e6-870d-c53ed4d1ee15.png)

**Comment by dinukadesilva** [comment]
Following items are to be discussed.

1. The way how we should divide notches.
2. How should we display large numbers. (value and notches)

**Comment by colinbdclark** [comment]
On the horizontal slider, would it make more sense to show the units in a horizontal orientation, rather than the vertical orientation you have here, for improved readability? Right now, a user will probably end up tilting their head sideways to read the labels on the slider's notches.

**Comment by dinukadesilva** [comment]
yeah..... that's something I wanted to ask here @colinbdclark 
I added them vertically because then the label length can be any. Otherwise, we have to come up with a way to limit the length of the labels.

On suggestion is we can have vertical labels and rotate them when the length is increased based on the increment.

**Comment by dinukadesilva** [comment]
I think we can divide notches based on the tick value.

Any idea about the how we should divide notches. ....

**Comment by dinukadesilva** [comment]
In terms of the responsiveness of this linear slider, I think we can do that based on the size of the parent element. So, in that case, I think we can have the following style. But, not sure how it would be interactive to the user.

![image](https://cloud.githubusercontent.com/assets/10680296/17077018/35e9e4ac-50df-11e6-8bd5-2e79fae03db1.png)

One limitation in this is the user should define the element height and width based on the style required. So I think we can let the user define the width of the slider as follows.

1. if the height is 100% the slider width can be set to wrap the container and adjust the pointer based on that
2. if the height has a numerical value, it can be set relative to the component.
