### ISSUE TITLE
[Knob] Some unusual characters are appeared on mouse-drag

### ISSUE THREAD

**Issue by dinukadesilva** [dinukadesilva/music-ctrls#59]

**Comment by simonbates** [comment]
Mozilla have a section on their Developer site discussing scripting SVGs:

- https://developer.mozilla.org/en-US/docs/Web/SVG/Scripting

And they have a section on preventing default behaviour:

"When writing drag and drop code, sometimes you'll find that text on the page gets accidently selected while dragging. Or if you want to use the backspace key in your code, you want to override the browser's default behavior when the backspace key is pressed, which is to go back to the previous page. The evt.preventDefault() method lets you do this."

**Comment by dinukadesilva** [comment]
@simonbates after adding evt.preventDefault() to the mousemove, the outside selection bug could be fixed.

**Comment by dinukadesilva** [comment]
To fix that disable icon displaying while dragging, evt.preventDefault() didn't work.
But, that could be fixed by making the component not selectable (using CSS)

**Comment by dinukadesilva** [comment]
#79 closes this
