### ISSUE TITLE
Use the "sisiliano" namespace as the root, rather than "fluid"

### ISSUE THREAD

**Issue by colinbdclark** [dinukadesilva/music-ctrls#6]
Currently, the Sisiliano components are nested within the <code>fluid</code> namespace. We typically reserve this namespace for Infusion itself. Instead, perhaps you will want to use <code>sisiliano</code> as your root namespace instead.

So, for example, <code>fluid.sisiliano.knob</code> will become just <code>sisiliano.knob</code>.

**Comment by dinukadesilva** [comment]
I added fluid.sisiliano since this is also another plugin for infusion. (like jQuery plugins)

**Comment by colinbdclark** [comment]
The <code>fluid</code> namespace is reserved only for Infusion itself. Each module should define its own custom namespace, to avoid confusion. Since this is a separate module, you can use your own namespace; <code>sisliano</code> seems like a good choice and will make your code a little shorter, too.

**Comment by colinbdclark** [comment]
You'll also want to update your test cases to use the <code>sisiliano.test</code> sub-namespace, rather than <code>fluid.test</code>.
